### ISSUE TITLE
Pattern Grid: Update patterns with new design

### ISSUE THREAD

**Issue by ryelle** [WordPress/pattern-directory#103]
Items should have a fixed height (195px in the design). Title and some meta information (see #100) appear under each pattern. On hover, the favorite & copy actions appear.

![](https://user-images.githubusercontent.com/541093/117468963-3a31f200-af23-11eb-83e4-3a3872a0cdb2.png)

**Comment by ryelle** [comment]
Patterns in the author's "my patterns" list can also have a status label, ex:

![pattern-status](https://user-images.githubusercontent.com/541093/117728208-256d8c80-b1b7-11eb-91ed-7f6edabf998c.png)

These patterns also have an extra actions dropdown:

![Hovered](https://user-images.githubusercontent.com/541093/117728808-ef7cd800-b1b7-11eb-88ec-d7d934cbfd4a.png)

![Owner Options Menu](https://user-images.githubusercontent.com/541093/117728811-f0ae0500-b1b7-11eb-8e5d-9a9bfa346c1c.png)

**Comment by shaunandrews** [comment]
> Items should have a fixed height (195px in the design)

My intention is that the rendered pattern should be contained within a box with a 1.5 aspect ratio — the height is dependent on the width of the column. The design uses a 960px max-width, and because of the way Figma renders box-shadows, the columns are actually meant to be 300px wide, which makes the rendered pattern 300x200px.

Here's a Figma that goes over how the grid should respond as the viewport changes: https://www.figma.com/file/bz4qs4jZCkqvQzPH2fmX6C/Pattern-Directory?node-id=1733%3A1

**Comment by ryelle** [comment]
> My intention is that the rendered pattern should be contained within a box with a 1.5 aspect ratio

Thanks for clarifying 👍🏻 

When do you think it should drop to that 2-column layout? We have existing breakpoints at 960 or 782 wide.

**Comment by shaunandrews** [comment]
782 seems fine if we don't want to add another breakpoint.
