### ISSUE TITLE
Horizontal Cards

### ISSUE THREAD

**Issue by schutzsmith** [WordPress/pattern-directory#179]
Cards are a basic design system component common in most websites.
---

## Pattern Title
Two column horizontal cards

## Pattern Categories
Columns, Gallery

## Screenshots
<img width="1117" alt="Screen Shot 2021-06-14 at 11 55 11 AM" src="https://user-images.githubusercontent.com/680204/121921863-681b0b00-cd07-11eb-8242-a2e7d21342c2.png">

## Image Credits
CC0 
https://search.creativecommons.org/photos/390c556e-48b2-44b5-8df6-20a2059202a9
https://search.creativecommons.org/photos/8b4970b4-8001-4212-aa6d-76295663334b

## Block Markup
https://gist.github.com/schutzsmith/86abea462a4d682ff02571966a9ca3f6

**Comment by schutzsmith** [comment]
Updated with more appropriate example text

**Comment by kjellr** [comment]
Hey there, thanks for this one. 

Unfortunately we can't use the border included above, since that's a style that's specific to the Twenty Twenty-One theme for the moment. In terms of the rest of the pattern, I think it's ok, but it could use a little iteration in terms of the imagery and colors. The monochromatic look is interesting, but this might be a good opportunity to try a pattern that uses the new duotone effects in Gutenberg.

I also feel like this looks quite like a Query block pattern (especially with the little "Categories" above the titles) — so part of me wonders if this is something we should just wait on this one and implement it a Query block pattern later on.

**Comment by beafialho** [comment]
I agree with @kjellr, this would make a great query block pattern later on!

**Comment by melchoyce** [comment]
Will we be able to do any query block patterns before the directory launches? Wondering if we should close this one for now & revisit.

**Comment by ryelle** [comment]
You _could_ create Query Loop patterns, but there's no post content on the site, so the preview won't render anything on the frontend. If you want to make Query Loop patterns, you could create some posts on the site?

**Comment by melchoyce** [comment]
Cool. I think we're going to need to spend more time thinking about what kind of posts to create, and then maybe kick off a drive just to work on query block patterns. In the meantime, I'm going to close this issue, but let's please revisit it later!
