### ISSUE TITLE
Pattern Submission: Stacked Media & Text with alternating alignment

### ISSUE THREAD

**Issue by 0aveRyan** [WordPress/pattern-directory#195]
This is a pattern I've used regularly across multiple sites since the Block Editor's launch as a way to create more-visual lists and weave stories that intermix visuals and words.

---

## Pattern Title
Stacked Media & Text with alternating alignment

## Pattern Categories
Images, Text

## Screenshots
![Screenshot of Stacked Media & Text with alternating alignment pattern showing three Media & Text Blocks](https://user-images.githubusercontent.com/9565066/122441883-db648d00-cf52-11eb-8758-24101101b80e.jpg)

## Image Credits
https://search.creativecommons.org/photos/138d50f8-2df8-4b29-8fed-4ac57758183c
"Arizona" by US Department of State is marked under CC0 1.0. To view the terms, visit https://creativecommons.org/licenses/cc0/1.0/

https://search.creativecommons.org/photos/68e9bc21-7ce1-4998-ac55-adb9d4c3db6b
"File:Canyon de Chelly - Flickr - romainguy.jpg" by Romain Guy from San Francisco, USA is marked under CC0 1.0. To view the terms, visit http://creativecommons.org/publicdomain/zero/1.0/deed.en

https://search.creativecommons.org/photos/58abe3ab-3d07-44ac-bf9a-6a694e79eb91
"Waterfall Trail on Fossil Creek" by Coconino NF Photography is marked under CC0 1.0. To view the terms, visit https://creativecommons.org/licenses/cc0/1.0/

## Block Markup
https://gist.github.com/0aveRyan/7f1c2ad06977b25c9b030c8f5d73fc41

**Comment by 0aveRyan** [comment]
Noted [the comment](https://github.com/WordPress/pattern-directory/issues/179#issuecomment-862326462) on #179 and I've removed borders from this submission:
https://gist.github.com/0aveRyan/6ff7e968091a8ca14a24d64ce155010d

**Comment by melchoyce** [comment]
Hey @0aveRyan! Thanks for your contribution.

I think we're going to hold off this one because we have quite a few media & text patterns in the release collection already:

- https://wordpress.org/patterns/pattern/media-text-with-image-on-the-right/
- https://wordpress.org/patterns/pattern/media-text-in-a-full-height-container/
- https://wordpress.org/patterns/pattern/event/
- https://wordpress.org/patterns/pattern/image-on-solid-color-with-description/

Please submit this once the directory is launched!
