### ISSUE TITLE
Pattern Submission: Partners logos

### ISSUE THREAD

**Issue by webmandesign** [WordPress/pattern-directory#207]
Title says it all.

---

## Pattern Title

Partners logos

## Pattern Categories

Gallery

## Screenshots

![Partners logos](https://user-images.githubusercontent.com/2456735/122525806-e8987f00-d019-11eb-855e-c55795a7480e.jpg)

## Image Credits

- https://www.rawpixel.com/image/556745/vintage-typewriter-illustration
- https://www.rawpixel.com/image/556608/vintage-turtle-illustration
- https://www.rawpixel.com/image/572898/fish-creature-vintage-drawing
- https://www.rawpixel.com/image/573354/antique-binoculars-drawing
- https://www.rawpixel.com/image/572412/antique-lantern-vintage-drawing

## Block Markup

https://gist.github.com/webmandesign/d807295bf3cac85f3ad25e37438c61d6

**Comment by beafialho** [comment]
Thank you @webmandesign, I think this one is perfect comparing to the other similar Partners pattern. If you agree, I'll close the other one.

Do you have any idea of fake content to replace the lorem ipsum text? I can also help with that if you want.

**Comment by webmandesign** [comment]
@beafialho Hi Beatriz,

Thank you for your feedback. If you mean my alternative partners logos pattern (#209), I personally prefer that one as it is more unique than this "standard" one :) But surely, feel free whatever suits the WP patterns directory. Is there any reason why both could not be added to the directory please?

As for "lorem ipsum" text, I indeed struggle with those, so any help would be very appriciated! :)
If you know of any more realistic dummy text generator I could use here, could you please let me know?

Thank you.

Oliver

**Comment by kjellr** [comment]
I prefer this one too — we have [a very similar pattern](https://wordpress.org/patterns/pattern/social-gallery/) to #209 already in the repository. 

I think the fact that this one is more "standard" is actually a good thing for now — it means more people will probably find it useful. 🙂

I have a small suggestion: Let's add captions so that it's clear these are companies and not just pictures. Here's a modified version with that update, and some new copy: 

<img width="1587" alt="Screen Shot 2021-06-18 at 11 41 43 AM" src="https://user-images.githubusercontent.com/1202812/122586134-446b0400-d02a-11eb-82d6-d6d29e9c7d00.png">

[Markup is here.](https://gist.github.com/kjellr/1f965c743be0d1efdecab30d61a8b1fc)

Let me know what you two think!

**Comment by beafialho** [comment]
@kjellr thanks, this looks great to me!

**Comment by webmandesign** [comment]
@kjellr @beafialho Thanks guys. I went ahead and updated my gist code accordingly. It's pity though that we can not use Gallery block for such captions. I think adding logos with Gallery block is more manageable for users.

**Comment by kjellr** [comment]
> It's pity though that we can not use Gallery block for such captions. I think adding logos with Gallery block is more manageable for users.

I agree! The way the gallery block displays captions doesn't work nicely for things like this. 😞 

I've added this pattern to the directory: 

https://wordpress.org/patterns/pattern/partner-logos/

I'll close https://github.com/WordPress/pattern-directory/issues/209 for now as well. Thanks for the submission!

**Comment by webmandesign** [comment]
Thank you!
