### ISSUE TITLE
Pattern Submission: Services

### ISSUE THREAD

**Issue by webmandesign** [WordPress/pattern-directory#211]
List of 3 services with icons.

---

## Pattern Title

Services

## Pattern Categories

Columns, Buttons

## Screenshots

![Services](https://user-images.githubusercontent.com/2456735/122577390-046c4700-d053-11eb-8d71-e6c3b1663b69.jpg)

## Image Credits

Icons from https://jam-icons.com/

## Block Markup

https://gist.github.com/webmandesign/122d4bf34c53fe115d86d2478e5a76aa

**Comment by kjellr** [comment]
Thanks for the submission! 

We're figuring out things about requirements for this pre-release collection as we go, and as part of that I have some thoughts on icons: In general, I think we should avoid patterns that use icons for now. Mostly because the experience for adding or changing icons right now isn't great — since they are static images, users can't change the icon color, and they won't be able to readily swap one icon for a similar one. I'm still wishing for https://github.com/WordPress/gutenberg/issues/16484 to make that better for us.

If we did include any patterns with modern icons, I think we should need to restrict them to only Dashicons/Gutenberg Icons. But as noted above, I'm not sure it makes sense, and I'm also not sure that icons relate nicely to the nature/art/history theme we're trying to carry through all of these patterns. 

(This would also impact patterns like https://github.com/WordPress/pattern-directory/issues/216, https://github.com/WordPress/pattern-directory/issues/194, https://github.com/WordPress/pattern-directory/issues/205, and https://github.com/WordPress/pattern-directory/issues/210)

**Comment by webmandesign** [comment]
In my pattern submissions I use SVG code inside "Custom HTML" block. I also provide source for the icons there. I understand this is not ideal and requires some explanation on how to change the icon and its color. Will there be some "Pattern description" field maybe when patterns directory is lounched?

If this is not acceptable still, can I replace those SVGs with images in my patterns?

I didn't know there is actually "nature/art/history theme" set for these patterns. Maybe I've missed that info, sorry about that.

**Comment by melchoyce** [comment]
Thanks for your patience @webmandesign! @kjellr published some additional clarifications on the Make/Design blog today: https://make.wordpress.org/design/2021/06/23/update-initial-patterns-for-the-patterns-directory/

**Comment by webmandesign** [comment]
Thanks for the update @melchoyce! I'll definitely check it out and update my submissions accordingly.

**Comment by melchoyce** [comment]
Revisiting this — I think between your great [partners pattern](https://wordpress.org/patterns/pattern/partner-logos/), https://wordpress.org/patterns/pattern/three-columns-of-text-with-buttons/, and https://wordpress.org/patterns/pattern/three-columns-of-text/, we're good with three column layouts like this. I'm going to close this issue, but of course feel free to submit this once the directory's open.
