### ISSUE TITLE
Pattern Creation: Submitted patterns should be saved as pending

### ISSUE THREAD

**Issue by ryelle** [WordPress/pattern-directory#370]
Initially, community-created patterns will need to go through manual review, so the creator should default all patterns to "pending". The submission flow relies on the "published" state to close the modal, so that will also need to be updated.

**Comment by tellyworth** [comment]
I think so, provided we can include an automated spam/abuse check in there. Those that pass the check would go straight to published, failures would go to pending or some other status.

@angelasjin what do you think?

**Comment by angelasjin** [comment]
I agree, including an automated spam/abuse check would be helpful. @tellyworth also suggested using keyword blocking, similar to what the Plugins team does, and I think that's an excellent recommendation. What would it take to include that? 

Then yes, those that pass the checks are published, and anything that doesn't would go to pending.

**Comment by tellyworth** [comment]
Thinking about this some more: rather than hard-coding the default pattern status to "published", what if it was configurable by an admin. That way if there's a flood of problematic patterns, the default could quickly be switched to "pending" without being dependent on a developer to deploy it. Put it in the hands of the admins who actually have to use it.

**Comment by ryelle** [comment]
So we'll also need a UI somewhere in wp-admin for moderators to change the submission status. Where would the best place for that be?
