### ISSUE TITLE
Update link to edit pattern in admin bar

### ISSUE THREAD

**Issue by richtabor** [WordPress/pattern-directory#387]
**Describe the bug**
Why are `https://wordpress.org/patterns/new-pattern` and `https://wordpress.org/patterns/wp-admin/post.php?post=10193&action=edit` both accessible for adding new patterns? 

They different experiences and its a tad confusing to be able to access both.

It seems `https://wordpress.org/patterns/new-pattern` is the correct view, as the Openverse media library loads there.

**Comment by ryelle** [comment]
Most people won't be able to access the view in wp-admin, you only can because you've been added to the site. `/new-pattern` is the correct place to create and edit patterns.

We should remove this link from the frontend, for non-admin users, since it goes to a permissions error screen.
<img width="270" alt="Screen Shot 2022-01-06 at 10 41 06 AM" src="https://user-images.githubusercontent.com/541093/148408986-0f4406f6-f67c-4849-b733-aa8acbf2e8d8.png">

Actually, maybe that link should go to the frontend edit page, since it's more intuitive for WP users than the dropdown.
<img width="537" alt="Screen Shot 2022-01-06 at 10 44 21 AM" src="https://user-images.githubusercontent.com/541093/148409501-3893f599-88cf-4889-92f6-2e8f771cde94.png">

**Comment by richtabor** [comment]
I was thinking that was the case — but yea, I agree with this: 

> Actually, maybe that link should go to the frontend edit page, since it's more intuitive for WP users than the dropdown
