### ISSUE TITLE
Pattern Submission: Wrong and inconsistent widths

### ISSUE THREAD

**Issue by webmandesign** [WordPress/pattern-directory#458]
**Describe the bug**
There is a discrepancy between nested blocks widths in pattern editor and in preview/pattern library.

Also, both are even wrong in terms of expected result.

**To Reproduce**
1. In pattern editor, create a pattern containing this blocks structure:
```
Group - full width
 ↳ Cover - wide aligned
   ↳ Image
 ↳ Columns - set 2 columns with some text
```

**Expected behavior**
Editor and preview should match.

**Screenshots**

![pattern-widths-issue](https://user-images.githubusercontent.com/2456735/159808524-1eb721f3-5f6f-44ba-aa23-db5ff604a630.jpg)

**Additional context**
I create my patterns in WordPress 5.9.2 installation with Twenty Twenty-One theme (with content widths set to match pattern library preview ones: 800px normal and 1000px wide aligned) and Gutenberg 12.8.1 plugin. So, the result produced with this setup is what I expect to see in pattern library, more or less.

**Comment by webmandesign** [comment]
The affected pattern was published now: https://wordpress.org/patterns/pattern/shadowed-image-with-description/

Is there any way I can use existing tools in pattern editor to achieve the desired layout? Is there a preferred way of setting up width in pattern editor? Can anybody provide some sort of schematic image for how widths of blocks are treated in pattern editor and library preview? Thanks.

**Comment by webmandesign** [comment]
Actually, I just went ahead for now and removed the full-width Group block wrapper so the widths are better now (still not perfect, what's expected) in https://wordpress.org/patterns/pattern/shadowed-image-with-description/

Please check the issue though as I plan to update the pattern once again when the issue is fixed.

**Comment by ryelle** [comment]
I think this is another issue caused by not using the Pattern Creator itself — the way block themes and classic themes handle layout is different.

The issue is that the cover is wide-aligned, so it has the 800 max width, but the columns block still goes edge to edge in the full-width container, right? In block-based themes, you can't set a width on Group children unless you've enabled "Inherit default layout." So I think the issue is that your cover had the wide class on it, from when you copied it out of a non-block-theme editor, and the columns has no alignment. As you can see in the screenshots, the preview & frontend match in both cases:

|   | Editor | Frontend |
|---|----|----|
| Default full-width block | ![align-full-editor](https://user-images.githubusercontent.com/541093/159997970-1b7a9fdf-c323-4510-a24c-9092984de105.png) | ![align-full](https://user-images.githubusercontent.com/541093/159997955-932cdeda-78c1-4e47-a038-59429b65a271.png) |
| Full-width group with "Inherit layout" | ![align-full-inherit-layout-editor](https://user-images.githubusercontent.com/541093/159997966-3bb300cc-7f16-4161-8849-2e22adf1e796.png) | ![align-full-inherit-layout](https://user-images.githubusercontent.com/541093/159997964-70e96e60-484f-40bd-8187-6c560fde706d.png) |

In the pattern you linked now, you should be able to set that columns block to wide-width to match the cover, or you could re-add the group block and toggle on "Inherit default layout."

**Comment by webmandesign** [comment]
Thanks for the feedback. It works now. I must have missed the content width setup before.
