### ISSUE TITLE
Allow Site Editing blocks on the Pattern Creator

### ISSUE THREAD

**Issue by priethor** [WordPress/pattern-directory#489]
### What problem does this address?
Currently, the Pattern Creator seems to be [based on the Post Editor](https://github.com/WordPress/pattern-directory/blob/ceaa393cd3908845c371c276f236724e3171e803/public_html/wp-content/plugins/pattern-creator/pattern-creator.php#L148), which limits the type of blocks that can be used. As of Gutenberg 13.2, this excludes the Template Part block from the Pattern Creator, but in upcoming Gutenberg versions, [more site editing blocks might be hidden from the Post Editor](https://github.com/WordPress/gutenberg/issues/31830).

### What is your proposed solution?
There are different ways to allow these site editing blocks, for instance:
- Using the Site Editor in the Pattern Creator.
- Customize the Pattern Creator to include certain blocks specifically

**Comment by ryelle** [comment]
The pattern creator uses a combination of the site editor packages and the post editor context, so how to work around that depends on how these blocks are hidden.

The creator already disables some blocks explicitly https://github.com/WordPress/pattern-directory/issues/23 because we can't control the data used to populate them (ex, Site Title, Page List) or they require permissions that non-user wporg users don't have (ex, Navigation). It also excluded the Template Part block before that was a core thing, since we don't have any template parts set up (and people copying the patterns to their sites wouldn't have those template parts).

**Comment by ryelle** [comment]
These have been added in #505
