### ISSUE TITLE
Pattern preview: Centered buttons do not appear in the center

### ISSUE THREAD

**Issue by beafialho** [WordPress/pattern-directory#523]
When creating patterns that have buttons justified to the center, these do not appear centered in the pattern preview.

<img width="952" alt="Captura de ecrã 2022-09-26, às 12 10 22" src="https://user-images.githubusercontent.com/65220155/192262311-5c519482-3128-4005-93d3-8df799610221.png">

<img width="951" alt="Captura de ecrã 2022-09-26, às 12 12 08" src="https://user-images.githubusercontent.com/65220155/192262384-fedffd83-c108-48aa-9583-a494700589df.png">

**Comment by ryelle** [comment]
This was fixed with the updates in #521.

<img width="1153" alt="Screen Shot 2022-09-26 at 2 09 37 PM" src="https://user-images.githubusercontent.com/541093/192349354-964a4a96-0994-4a49-92ba-b4409d3cdadd.png">

<img width="937" alt="Screen Shot 2022-09-26 at 2 10 30 PM" src="https://user-images.githubusercontent.com/541093/192349528-7eb72a28-a058-433d-a0b4-84c5a526300a.png">
