### ISSUE TITLE
Pattern Previews: Site Logo placeholder is too large

### ISSUE THREAD

**Issue by ryelle** [WordPress/pattern-directory#544]
When an image is added, the site logo block defaults to 120px wide. In the pattern preview, that limit is not set, so the site logo expands to the full 1000px width of the mock/placeholder image.

Example affected pattern: https://wordpress.org/patterns/pattern/simple-header-with-tagline/

Adding `is-default-size` to `wp-block-site-logo` fixes the size issue.

@beafialho Should an empty Site Logo block still use the (W) logo as a placeholder, or should it switch to the image placeholder like #538?

**Comment by beafialho** [comment]
> @beafialho Should an empty Site Logo block still use the (W) logo as a placeholder, or should it switch to the image placeholder like https://github.com/WordPress/pattern-directory/pull/538?

I have mixed feelings on this one 🤔 The placeholder may not look intuitively like a logo, because of its size and minimalism. @jasmussen what are your thoughts?

**Comment by jasmussen** [comment]
My quick instinct is that patterns that feature site logos are likely to be headers, or cross into "wireframe" territory, and thus be a bit more utilitarian in nature. The gutenberg placeholder design is meant to very literally look like a wireframe, for that same reason, so if it was possible to show this placeholder wireframe in the pattern preview, I think I would lean towards that. 

This would match the "Replace header" flow in the block editor, which gives you this look when you don't have a site logo defined:

<img width="722" alt="Screenshot 2022-11-29 at 13 10 23" src="https://user-images.githubusercontent.com/1204802/204525656-4686045c-7733-451c-95be-a0159637c68d.png">

Keep in mind that this wireframe placeholder is meant to both be susceptible to explicit width/height definitions, as well as the style variation (such as rounded). I would expect border and radius in the future as well, so that even if a wireframe, it can be expressive.

**Comment by beafialho** [comment]
I agree. Let's align the site logo placeholders with the approach above then 👍 Thanks for you input!

**Comment by richtabor** [comment]
> @beafialho Should an empty Site Logo block still use the (W) logo as a placeholder, or should it switch to the image placeholder like https://github.com/WordPress/pattern-directory/pull/538?

> I agree. Let's align the site logo placeholders with the approach above

Yes, we should switch from using the (W) to use the site logo block's placeholder state instead. This may resolve the logo size issue, without having to add a class to each instance of the site logo. 

For reference, here's the current state of the WordPress.org-authored header patterns atm. 😬

<img width="1069" alt="CleanShot 2023-01-30 at 14 16 47" src="https://user-images.githubusercontent.com/1813435/215573237-db87a9a5-00bd-47ff-b2bf-0df6bccc819f.png">
