### ISSUE TITLE
New Query Loop (Posts) patterns are not rendering properly within the editor

### ISSUE THREAD

**Issue by richtabor** [WordPress/pattern-directory#552]
**Describe the bug**

I was testing [the new Query Loop patterns](https://github.com/WordPress/gutenberg/issues/44140#issuecomment-1419705646) and discovered that they do not render properly within the editor BlockPreview, or when inserted. You end up with post content from the posts published for the Pattern Directory. 

But if you copy/paste the [pattern](https://wordpress.org/patterns/pattern/fullwidth-posts-titles-with-dates/) from the directory, it renders properly. 

**To Reproduce**
1. Run Gutenberg trunk
2. Open Patterns inserter
3. Click on the "Posts" category
4. Scroll down till you see the three new posts patterns loaded from the directory
5. See error 
6. Try inserting one of the patterns
7. See error

**Expected behavior**
The pattern is inserted properly as a Query Loop block.

**Screenshots**
<img width="648" alt="CleanShot 2023-02-07 at 18 14 01" src="https://user-images.githubusercontent.com/1813435/217388915-e213b99d-0d2b-4e74-957c-74f4594c3cd7.png">

**Additional context**
This could be tied to the queryID attribute within the Query Loop block. I've removed it manually from [this pattern](https://wordpress.org/patterns/pattern/fullwidth-posts-titles-with-dates/) to see if that resolves the issue. 

If so, we should strip that out autonomously.

**Comment by ryelle** [comment]
So I think this has the same root cause as this GB issue: https://github.com/WordPress/gutenberg/issues/42862, it seems like the query isn't cleared from the query block — because what you're seeing there is actually the content from the last post in the query in the pattern itself.

I have a workaround I'll push shortly, but it's strange that [resetting the query here](https://github.com/WordPress/gutenberg/blob/c4e0a21c988a82b2d19655c5b825177d7aecd9c2/packages/block-library/src/post-template/index.php#L105-L110) isn't actually resetting it.
