### ISSUE TITLE
Pattern statuses

### ISSUE THREAD

**Issue by coreymckrill** [WordPress/pattern-directory#56]
* `draft` The pattern has not been submitted to the directory yet, or it was submitted but failed automated validation checks. See #36 
* `awaiting-review` (or maybe just use `pending`?) The automated checks determined that a human review is also needed. This could also be used when a published pattern gets flagged as inappropriate.
* `declined` The pattern was declined by a human reviewer. See #16 
* `publish` The pattern passed automated checks and/or human review. It is now published in the pattern directory and appears in searches via the API.
* `removed` The pattern was previously published, but was removed either by the author or a moderator. See #16 

There is also some discussion in #16 of having patterns that are only available to the pattern author until the author chooses to publish them. So an additional status might be:

* `private` The pattern has been submitted, and passed automated checks, but has not been published by the author.

**Comment by ryelle** [comment]
I think `submitted` should be `draft` - I see the word "submitted" and I think it's done and awaiting review.

Do you think we need a special status for `invalid`? If it doesn't pass validation checks, I think it would just not move on from draft. Maybe this should be a meta value on the pattern, rather than a custom status?

The `private` idea is not a launch requirement, but good to keep in mind.

**Comment by coreymckrill** [comment]
Ok, updated to consolidate `draft`/`invalid` into one status. Maybe we don't even need to save a meta value on the pattern if it's invalid, if the author will receive a detailed message about the validation errors in the UI.
