### ISSUE TITLE
Email notifications about pattern changes

### ISSUE THREAD

**Issue by coreymckrill** [WordPress/pattern-directory#58]
When the status of a pattern changes (#56), and possibly in some other cases, the pattern author should receive an email notification about the change. This serves to ensure they are informed when e.g. a pattern is removed from the directory by a moderator for some reason, and also to alert them to possible unauthorized access to their account.

**Comment by ryelle** [comment]
Does this supersede #19?

**Comment by coreymckrill** [comment]
Oops, missed that. This one is a bit more detailed, so I'll close the other one.

**Comment by coreymckrill** [comment]
Thinking through this a bit more. It seems like it wouldn't be great if the pattern creator received an email that just said, "Your pattern has been unpublished from the pattern directory" without an explanation. #105 is intended to provide an _internal_ explanation for why a pattern status is changed, but I'm not sure it's what we'd want to put in the email either.

So, if we're going to tell people when their pattern changes, we need to provide them with some resources to get more information, so that they have recourse. But we also need to do that in a way that won't open up the pattern moderators to harassment and abuse.

**Comment by coreymckrill** [comment]
Moving this out of the Initial Launch milestone because it seems like we should see how pattern moderation ends up working in practice before we try to build this.

**Comment by angelasjin** [comment]
The Themes team has kindly agreed to sharing their email address for email notifications and communication with pattern contributors. What do you think about the following auto-notifications through `themes@wordpress.org`?

**If a pattern is published**

> Hello! 
> 
> Thank you for submitting your pattern, `TITLE`. It's now live in the Block Pattern Directory!

**If a pattern is unpublished**

> Hi there!
> 
> Thanks for submitting your pattern. Unfortunately, your pattern, `TITLE`, has been flagged for removal due to the following reason: `REASON`. Your pattern has been unpublished from the Block Pattern Directory at this time, and will receive further review. If the pattern meets the guidelines, we will re-add it to the Block Pattern Directory. Thanks for your patience with us volunteer reviewers! 

Can we also set it up so that these auto-notifications are automatically tagged in HelpScout with `block-pattern-creator`?

I think if we do remove a pattern permanently, reviewers can send an email through a saved reply in the Themes HelpScout instance. How does this sound?

**Comment by coreymckrill** [comment]
> Can we also set it up so that these auto-notifications are automatically tagged in HelpScout with block-pattern-creator?

@angelasjin so are you thinking that these messages would be sent to both the user who created the pattern and to HelpScout?

**Comment by angelasjin** [comment]
No, and I can see how my comment there suggests that! I think the initial email can go to the user only, but if they respond to it, I think it makes sense that it lands in `themes@wordpress.org`, and hopefully tagged with `block-pattern-creator`. What do you think about that?

**Comment by coreymckrill** [comment]
Ok, yep, we can add a `reply-to` header to send replies to HelpScout 👍

**Comment by coreymckrill** [comment]
@angelasjin @ryelle as I'm working on this, I'm realizing we need to distinguish between patterns that have been temporarily unpublished until they have been manually reviewed (because of flags or spam filter), **vs.** patterns that have been unlisted from the directory after manual review, which is more likely permanent. What do you think about these:

**Flagged for review**

> Subject: Pattern being reviewed
>
> Hi there!
>
> Thanks for submitting your pattern. Unfortunately, your pattern, TITLE, has been flagged for removal due to the following reason:
>
> REASON
>
> Your pattern has been unpublished from the Block Pattern Directory at this time, and will receive further review. If the pattern meets the guidelines, we will re-add it to the Block Pattern Directory. Thanks for your patience with us volunteer reviewers!

**Unlisted**

> Subject: Pattern unlisted
>
> Hello,
>
> Your pattern, TITLE, has been unpublished from the Block Pattern Directory due to the following reason:
>
> REASON
>
> If you would like to resubmit your pattern, please make sure it follows the guidelines:
>
> GUIDELINES LINK

**Comment by ryelle** [comment]
This makes sense to me. I think the existing statuses should work for "flagged for review", maybe sending on these status changes:

- `publish -> pending`: A published pattern moving to pending is almost certainly due to crossing the flags threshold
- `[any] -> pending-review`: This is the spam status, any pattern moved here is suspected of spam (either by the tool or a human reviewer moving to unlist)

For the unlisted patterns, we have [some reason strings](https://github.com/WordPress/pattern-directory/blob/6cea384136a1948150ba75b714ea4405e394bc41/public_html/wp-content/themes/pattern-directory/src/components/pattern/status-notice.js#L8), but I'm actually considering moving those into the tax term description so they can be updated in the admin (and shared between JS/PHP). I also want to add two more reasons for Spam & Non-English. The [way the reason is saved](https://github.com/WordPress/pattern-directory/issues/446) might change before full-launch too.

It's possible a pattern might be moved from `published -> pending-review -> unlisted` in one moderation session, as that's the fastest way to remove a published spammy pattern. This might be more likely when patterns default to publish.

**Comment by coreymckrill** [comment]
@ryelle 

> For the unlisted patterns, we have [some reason strings](https://github.com/WordPress/pattern-directory/blob/6cea384136a1948150ba75b714ea4405e394bc41/public_html/wp-content/themes/pattern-directory/src/components/pattern/status-notice.js#L8), but I'm actually considering moving those into the tax term description so they can be updated in the admin (and shared between JS/PHP).

Does this mean the Reason taxonomy would also be registered for the pattern post type (in addition to the flag post type)? Seems like when a pattern gets unlisted, it could be assigned whatever term was the prevailing reason for its removal.

> It's possible a pattern might be moved from published -> pending-review -> unlisted in one moderation session, as that's the fastest way to remove a published spammy pattern.

In which case the user would get two emails in quick succession. But I think that would be ok.

**Comment by ryelle** [comment]
> Does this mean the Reason taxonomy would also be registered for the pattern post type (in addition to the flag post type)? Seems like when a pattern gets unlisted, it could be assigned whatever term was the prevailing reason for its removal.

Yep, right now it saves the unlisted term-ID as meta, but what you described is how I'd rather it work. Well, not exactly, because a moderator still needs to manually pick the reason, but auto-detecting could help.

> In which case the user would get two emails in quick succession. But I think that would be ok.

👍🏻
