### ISSUE TITLE
Issue with block search bar on new pattern creation page

### ISSUE THREAD

**Issue by harshgajipara** [WordPress/pattern-directory#596]
There is an issue with keyword "search" on block search bar on new patter creation page on wordpress.org. 
https://wordpress.org/patterns/new-pattern/

When try searching with keyword "search", the sidebar shows unexpected behaviour as shown in the video below.

[New Pattern _ WordPress.org.webm](https://github.com/WordPress/pattern-directory/assets/60835353/15174d44-36f9-4989-9f02-6ddaf3e87c35)

**Comment by pkevan** [comment]
Thanks for the report - can you provide some further details to help debug this - browser, logged in/out, anything else which you think might be relevant.

I was unable to reproduce this in Chrome 115 logged in and out.

**Comment by harshgajipara** [comment]
Sure here are the details. It's happening when logged in. But only with the keyword "search". When we type    "sea"  In the search bar then it starts shaking. 

OS: windows 10
Browser: chrome - 115.0.5790.110

**Comment by pkevan** [comment]
Thanks - I wonder if this is a style issue on windows only (i'm looking at it from Macos)

**Comment by ryelle** [comment]
It looks like this was an issue with the search pattern loading and creating a scroll, then resizing and removing the scroll. But I don't think this is issue anymore, since the block inserter layout has updated. The tabs and search bar have switched, and patterns have been disabled from the pattern creator's inserter.

<img width="346" alt="Image" src="https://github.com/user-attachments/assets/2abbafda-f0b7-4ba7-b4fc-0f77e0f0c500" />
