### ISSUE TITLE
Locale parameter cause fatal error

### ISSUE THREAD

**Issue by pkevan** [WordPress/pattern-directory#625]
**Describe the bug**
When the locale parameter is sent, using array notation, the request causes a fatal error.

**To Reproduce**
1. Go to (https://api.wordpress.org/patterns/1.0/?page=1&per_page=100&order=desc&orderby=date&locale%5Badministrator%5D=1&wp-version=6.2.2&pattern-keywords=11)
2. See error in alerts channel, or sandboxed in error log.

Possibly related to the core updates to l10n, but unsure. Tried to work around the issue by unsetting the `locale` URL parameter and global in https://meta.trac.wordpress.org/browser/sites/trunk/api.wordpress.org/public_html/patterns/1.0/index.php#L49, but didn't seem to help.

**Comment by ryelle** [comment]
I think this is an issue with some sites, not a widespread API issue — looking at the logs in the alerts channel, all but one are for the same site. The code that generates that value hasn't changed — `get_locale` on trunk & 6.2.2 (what that site uses) should return a string in both cases.

The other site that triggered this error happened once, on Feb 10, and it looks like something went wrong with the request.

`https://wordpress.org/patterns/wp-json/wp/v2/wporg-pattern?page=1&per_page=100&order=desc&orderby=date&locale[0][message]=<strong>New in Yoast SEO Premium 19.2:</strong> Did you know that you can now <a href="https://www.celeritydiscovery.com/wp-admin/admin.php?page=wpseo_dashboard`

Anyway, I think filtering out non-string locale values makes sense, but I also ran into this: 

> Tried to work around the issue by unsetting the locale URL parameter and global, but didn't seem to help.

It looks like the $_GET values are still passed through to the `w.org/patterns` API request, regardless of how we set `$query_args`. The following _does_ seem to work, but is it okay/enough to unset a $_GET value like this?

```
if ( isset( $query_args['locale'] ) && ! is_string( $query_args['locale'] ) ) {
	unset( $query_args['locale'] );
	unset( $_GET['locale'] );
}
```

Actually, it looks like the `$query_args` should be set as we expect, it's handled by `api/public_html/wp-init.php` since we set `$wp_init_query = true`. But that happens _after_ loading WP, so the incorrect `locale` is still passed through to the setup. Maybe this is where the recent core changes impact it, it's setting up the locale earlier now?

Maybe the query setup part of `wp-init.php` should also happen before wp-load.php is called, but that would impact many of the endpoints.

**Comment by pkevan** [comment]
> looking at the logs in the alerts channel, all but one are for the same site.

I did wonder if there was a request which produced this request but couldn't figure out where it was coming from - did you have any insights @ryelle? It seems like the `wp-version=6.2.2&pattern-keywords=11` might give a clue, but it wasn't obvious where this was coming from.

**Comment by ryelle** [comment]
Do you mean where in core? It's called in [the `/wp-json/wp/v2/pattern-directory/patterns` endpoint](https://github.com/WordPress/wordpress-develop/blob/1bb5c2c5ce7ac8e472758774fda8032708c20412/src/wp-includes/rest-api/endpoints/class-wp-rest-pattern-directory-controller.php#L89), which is used to load (and locally cache) the core-provided w.org patterns. The `wp-version=6.2.2` says that the requesting site is using 6.2.2, and `pattern-keywords=11` is the request for ["core" tagged patterns](https://wordpress.org/patterns/wp-admin/edit.php?wporg-pattern-keyword=core&post_type=wporg-pattern&post_parent=0&post_status=publish).

Tracking it backwards from there, that local api endpoint [is used in `_load_remote_block_patterns`](https://github.com/WordPress/wordpress-develop/blob/1bb5c2c5ce7ac8e472758774fda8032708c20412/src/wp-includes/block-patterns.php#L211), which does the API request and then registers the resulting patterns.

The `locale` param should reflect the site/user's locale so that Spanish sites get Spanish patterns, etc. So I suspect something on that site is incorrectly filtering the locale.

**Comment by pkevan** [comment]
Ah - i'd misunderstood the logging messages, and thought the requests were coming from `wordpress.org/patterns` but presumably the source is indicating the API requests being redirected to the patterns API:

```
Source: GET https://api.wordpress.org/patterns/1.0/?page=1&per_page=100&order=desc&orderby=date&locale%5Badministrator%5D=1&wp-version=6.2.2&pattern-keywords=11 (=> GET https://wordpress.org/patterns/wp-json/wp/v2/wporg-pattern?page=1&per_page=100&order=desc&orderby=date&locale%5Badministrator%5D=1&wp-version=6.2.2&pattern-keywords=11 )
```

**Comment by ryelle** [comment]
Yeah, it's kind of a three layer process — Client site wants to load patterns, so it requests `local-site.com/wp-json/wp/v2/pattern-directory/patterns`; which proxy-calls `api.w.org/patterns`, which finally calls `w.org/patterns/wp-json/wp/v2/wporg-pattern` to load the default post-type endpoint for patterns on the Pattern Directory.

**Comment by pkevan** [comment]
It doesn't seem to leave us many options in protecting against invalid input, since the parameters are in the URL, so perhaps unsetting the `$_GET` var is the thing to do.

**Comment by dd32** [comment]
This is a fatal error in PHP 8.1, so we do have to do something to protect against the invalid input.

The backtrace for the fatal is fairly odd, as the locale is just-in-time loaded.
> ```WordPressdotorg\API\Patterns\main, require_once('wp-init.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('plugins_loaded'), WP_Hook->do_action, WP_Hook->apply_filters, Jetpack_Gutenberg::load_independent_blocks, include_once('/plugins/jetpack/extensions/blocks/contact-info/contact-info.php'), Automattic\Jetpack\Blocks::jetpack_register_block, register_block_type, register_block_type_from_metadata, translate_settings_using_i18n_schema, translate_with_gettext_context, get_translations_for_domain, _load_textdomain_just_in_time, WP_Textdomain_Registry->get, WP_Textdomain_Registry->get_path_from_lang_dir, WP_Textdomain_Registry->set```

After a lot of debugging, I've traced it back to a filter that was not properly validating the requested locale is valid:
https://github.com/WordPress/pattern-directory/blob/f4558efe6635da2dd59cc669f965a2da1716caea/public_html/wp-content/plugins/pattern-translations/pattern-translations.php#L127-L134

See #626

**Comment by dd32** [comment]
> Maybe the query setup part of wp-init.php should also happen before wp-load.php is called, but that would impact many of the endpoints.

It does look like this part of `wp-init.php` is a bit weird.. It's a little odd that `$_GET` is still set, although the `REQUEST_URI` is set differently.. 

In this case, I don't think it'd have made a big difference, except it would've made unsetting the locale parameter at the API level work properly.

I'd not be afraid of changing the behaviour of `wp-init.php`, but I'm hesitant to do myself it unless we have a use-case that shows the shortcoming properly.
