### ISSUE TITLE
Create New Patterns Page is using post editor when it supposed to be a Site Editor when you create patterns

### ISSUE THREAD

**Issue by Saoming** [WordPress/pattern-directory#628]
**Describe the bug**
Create New Patterns Page uses a post editor when it is supposed to be a Site Editor when you create patterns. 

**To Reproduce**
Create Patterns from Site Editor as type wp_block 

**Expected Results**

<img width="1440" alt="Screenshot 2024-03-07 at 14 35 36" src="https://github.com/WordPress/pattern-directory/assets/23113806/f11815a2-1f89-4c0b-920d-42cdcf043c63">

**What I am getting right now:**
<img width="1440" alt="Screenshot 2024-03-07 at 14 35 28" src="https://github.com/WordPress/pattern-directory/assets/23113806/babf03ed-cd5a-4dca-8d55-a0129938a061">

**Comment by miksansegundo** [comment]
This issue sounds like https://github.com/WordPress/pattern-directory/issues/554, which was previously fixed by https://github.com/WordPress/pattern-directory/pull/557

**Comment by miksansegundo** [comment]
I tested the toggle for "Layout: Inner blocks use content width" in the pattern directory editor, and it seems not to be working because the styles are missing.

<img width="254" alt="Screenshot 2567-03-07 at 16 03 27" src="https://github.com/WordPress/pattern-directory/assets/1881481/93b8dd35-1a10-45a3-9ff6-146a8027beb4">

I was expecting to find the following styles because they are present in the Site editor, but they are not present in the pattern directory editor:

<img width="617" alt="Screenshot 2567-03-07 at 16 03 40" src="https://github.com/WordPress/pattern-directory/assets/1881481/e20298f7-4119-4b94-abc9-9a346e3e94bd">

The only styles that I can find are the following:

<img width="518" alt="Screenshot 2567-03-07 at 16 04 18" src="https://github.com/WordPress/pattern-directory/assets/1881481/1872c4c3-5391-436b-8260-17b2b769fd52">

@Saoming mentioned to me that those styles were working last month. I'm wondering if this recent [commit](https://github.com/WordPress/pattern-directory/commit/e20e550ccd05dcb22ef96a38c77961c50a83bdfd) is somehow related to the issue.

**Comment by ryelle** [comment]
Closing this in favor of the discussion on #658.
