### ISSUE TITLE
Redesign: Filtering "core" on non wporg author returns 404.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/pattern-directory#637]
**Describe the bug**
If I apply the "Curated" filter to an author view. I get a 404. I would expect to receive an empty list.

Example Url: https://wordpress.org/patterns/author/ignaziodimaio?curation=core

**Comment by ryelle** [comment]
I think this is an issue with the way the theme-switcher works & the fact that I've added `curation` as a query var in the theme — it's working locally for me.

<img width="1215" alt="Screenshot 2024-03-12 at 2 05 56 PM" src="https://github.com/WordPress/pattern-directory/assets/541093/11c3306a-6436-458a-8828-b09ffbbebeb1">

On the other hand, we probably don't need the Curation dropdown on authors, since IIRC only wordpressdotorg will have "curated" patterns.

**Comment by StevenDufresne** [comment]
Okay, feel free to close.

**Comment by ryelle** [comment]
> Okay, feel free to close.

👍🏻  — I'll make a note to test this again once the theme is launched and the permalinks are flushed "for real"
