### ISSUE TITLE
Pattern Directory Structure: PHP and JS. 

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/pattern-directory#66]
How do we want to organize the front end?

- Do we want to create a `front-page.php` for the grid?
- We currently have an `index.js` file in `src` that pulls in the pattern preview component. Are we going to leverage that `index.js` and turn it into an _app_ the same way an SPA works? 
   - If so, do need a router?
 - Alternatively, do we want to load a separate JS payload per _page?_ 

@ryelle @iandunn Thoughts?

**Comment by ryelle** [comment]
I was already working on an idea here (for #62 ), so here's a quick overview of my thoughts… (I'll have at least a WIP PR up sometime today)

> Do we want to create a `front-page.php` for the grid?

The grid is on all archive pages & search results, so no, we would need to use it on all archives too. I ended up creating an `index.php`, and using a filter [like this](https://meta.trac.wordpress.org/changeset/10857) to override the archive & search templates to use that `index.php`.

I wanted to make this work with a non-SPA (PHP/HTML-first) approach, but overall the whole browsing experience is meant to be so interactive that I think it'll be easier to make a self-contained "SPA"-style component. And I just say SPA-style because I think we should keep the JS component inside the page content frame, and just for the grid browsing view.

> Are we going to leverage that `index.js` and turn it into an app the same way an SPA works? 

My intention was to have two main "components" (and possibly other functionality) in `src/index.js`. I set that file up to be an initializer of sorts, depending on the content on the page. So if it sees `.pattern-preview__container`, it will set up the resizable preview. If it sees a grid container, it will start up the grid component (WIP). This is pretty much where I stopped last night.

Ideally the default WP term archive & search URLs will still work, but whether we need a whole router I'm not sure yet. The navigation for most filters will "just" be clicking through different archive links, with dynamic loading of the matching patterns, and the ability to load more patterns infinite-scroll style.

> do we want to load a separate JS payload per page?

Maybe later, but I don't think we need to do that preemptively. It probably depends on the router (if we need to include something like react-router/reach-router, we don't need that on the single page).

**Comment by StevenDufresne** [comment]
@ryelle While thinking about the JS structure, can you consider how we plan on organize how we fetch data? I'm almost ready to grab the taxonomies to fill the grid menu. I'm not too fussed about how we want to do it, just a general direction will help me with next steps.

For example:
1. Create a redux like store
2. Create a provider that stores the information and wraps the 'app'
3. Have high-level controls/modules that call via rest api
4. Grab object that has been written to the document... etc..

**Comment by ryelle** [comment]
I thought we would use the gutenberg data infrastructure - [`wp.data.register`](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-data/#register), etc. We can fetch the data with `apiFetch` in resolvers, and then interact with it using `useSelect` & `useDispatch`. ([this series is a deep dive into wordpress data,](https://unfoldingneurons.com/2020/wordpress-data-putting-it-all-together-and-registering-your-store) though some of the minor details have changed)

Initial thoughts on the things we want to track:

- The list of patterns
- The list of "stuff to query on" (taxonomy terms)
- The query being using to show this list (filters & sorting order)
- Patterns the current user has favorited (if logged in)

So I think the core data tools will work out fine for this.

**Comment by StevenDufresne** [comment]
I'll close this as it's taking shape in the associated Pull Requests.
