### ISSUE TITLE
Block theme: using category nav bar on favorites (or author view) navigates me away.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/pattern-directory#668]
**Describe the bug**
If I click on the category navigation bar on my [favorites page](https://wordpress.org/patterns/favorites/) or the [author view](https://wordpress.org/patterns/author/wordpressdotorg/), it navigates me away to the main search page.

For favorites, I wonder if we can just remove it. I don't know that people viewing their patterns need to view them by category. Maybe it's the same for the author view.

| Screenshot |
|--------|
| <img width="892" alt="Screenshot 2024-04-15 at 1 19 39 PM" src="https://github.com/WordPress/pattern-directory/assets/1657336/2c272f75-753c-4a3c-b0a0-413980e91d12"> |

**Comment by ryelle** [comment]
~I also noticed this last week but apparently forgot to make an issue, so thanks!~ The issue is here: https://github.com/WordPress/pattern-directory/issues/663, but doesn't mention the author archive.

This functionality [should be working](https://github.com/WordPress/pattern-directory/blob/ba0395d9f28e357ec8000ec34b19d0be78b07e14/public_html/wp-content/themes/wporg-pattern-directory-2024/inc/block-config.php#L98-L109), so something broke. 

For some data, since I was curious, the vast majority of people have only one page of favorites, but there are 200+ with >24, and almost 50 with 100+ (out of almost 3,200 users with favorites). So not many would need this on Favorites, but it did work before, and works this way on the old theme.
