### ISSUE TITLE
Block theme: How do I clear my filtered search?

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/pattern-directory#669]
**Describe the bug**
We no longer have an "all" category. If I click `Featured`, and search, it will search for the keyword inside the `Featured` category. That is expected.

How do I search for my keyword amongst all the categories if I have already selected one? [Start here](https://wordpress.org/patterns/categories/gallery/) for example.

**To Reproduce**
1. Go to https://wordpress.org/patterns/?new-theme=1
2. Click on `Featured`
3. Search for `pricing`
4. Notice the result set is relevant.
5. Try to search all patterns now.

**Comment by ryelle** [comment]
You can back out using the breadcrumbs to get back to the "All patterns" page, so it's not impossible - but not exactly obvious either.

![Screen Shot 2024-04-15 at 11 26 56](https://github.com/WordPress/pattern-directory/assets/541093/104a8a5c-af84-4dca-8f7f-194f185b6a22)

@WordPress/meta-design What do you think?

**Comment by jasmussen** [comment]
I'd tend to echo Kelly that the breadcrumbs work reasonably for this, and the bery visible active state for the particular tab you're in is good indication of context. I also didn't mind having the "All" tab.

**Comment by StevenDufresne** [comment]
Although we have technically navigated to a new page, I don't think users consciously note the navigation when they click on a category link, especially given how most modern directories are single-page web pages with no post-back. 

As @ryelle  mentions, I agree that reversing filtering by navigating to a new page doesn't feel obvious.

Assuming [this is where the "all' button was removed](https://github.com/WordPress/wporg-parent-2021/pull/127#issuecomment-1997666245), I would suggest we add it back.

**Comment by fcoveram** [comment]
> Assuming https://github.com/WordPress/wporg-parent-2021/pull/127#issuecomment-1997666245, I would suggest we add it back.

True. Removing the "All" tab came from a conversation about the multiple selection flow where "all options selected" shows the same results as "all options unselected". The single selection demands an option to show everything, and the current demo site has it correctly. Screenshot below.

<img src="https://github.com/WordPress/pattern-directory/assets/895819/5e1470f4-6d5d-410d-9e66-79ff4130523b" width="300">

---

Therefore, and since tabs behave as single selection views, it makes sense to bring back the "All" option.

Landing on the page with all items from a breadcrumb link is definitely a tricky interaction. Although the breadcrumb has the link included, its purpose is primarily about site location. Due to the interaction context, the "All" tab should be next to the rest in the first position.

**Comment by ryelle** [comment]
Okay, I'll bring back the "All" option in the category nav menu 🙂

**Comment by ryelle** [comment]
I've added "All" back to the category menu & the status menu:

Home
<img width="1261" alt="Screenshot 2024-04-16 at 11 29 29 AM" src="https://github.com/WordPress/pattern-directory/assets/541093/36b34fb9-09df-4fd8-8d30-1f07db81ad9b">

My Patterns
<img width="1292" alt="Screenshot 2024-04-16 at 11 29 36 AM" src="https://github.com/WordPress/pattern-directory/assets/541093/524f9853-3205-4602-9b51-b4584cc61ee0">
