### ISSUE TITLE
Block theme: No way to identify author if they only have 1 pattern.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/pattern-directory#670]
**Describe the bug**

In https://github.com/WordPress/pattern-directory/pull/657, we decided to hide the "More from this author" section if the author only has one pattern, the one you are viewing, because the section was empty. Most authors only have 1 pattern.

The oversight made was that in the new designs, this is the only link to the author whereas before it was on the card in the grid view as well. I'm not sure what would be best here...

@WordPress/meta-design Any thoughts on this? Should we render the section but say "the author has no more patterns?

| Old | New |
|--------|--------|
| <img width="324" alt="Screenshot 2024-04-15 at 1 47 36 PM" src="https://github.com/WordPress/pattern-directory/assets/1657336/700cc027-6ae2-4409-a42b-fba05810d47b"> | <img width="389" alt="Screenshot 2024-04-15 at 1 47 27 PM" src="https://github.com/WordPress/pattern-directory/assets/1657336/62e62ad6-39e4-4b4e-ae2d-ed6088f58a02"> |

**Comment by jasmussen** [comment]
It sounds like, and correct me if I'm wrong, that the main issue is there's no identifying who the author is. Can we reintroduce the author-name potentially here?

![Screenshot 2024-04-15 at 08 56 38](https://github.com/WordPress/pattern-directory/assets/1204802/b6ce6034-adbe-4d10-a032-f507618a501a)

That is, to the right of the star button, show the author name? If it feels duplicative we can remove it from the "More from this author" section, when that section is present. 

We can then, on the permalink for the author, show the single pattern that this author has added, so it's clear that there's just the one.

**Comment by ryelle** [comment]
I've tried it here, what do you think @jasmussen ? I don't think it's too duplicative because the 600px-tall preview breaks up the page, you're unlikely to notice both at once. I also made this not a link, so that it's not a repeated link on the page (a11y concern), and if the user only has this one pattern, there's no need to link to their author-archive page. The author name in the "more from …" still has the archive link if the viewer wants to see even more patterns.

![Screen Shot 2024-04-15 at 10 33 08](https://github.com/WordPress/pattern-directory/assets/541093/d15f861a-d221-436e-9401-3f3d315722da)

**Comment by jasmussen** [comment]
I could go with the duplication, or just the author at the top. I think we can even start with one and move to the other depending on how that feels.

**Comment by ryelle** [comment]
Okay, if you have no strong opinion, I'll go with what I've got in that screenshot.
