### ISSUE TITLE
Retrieving pattern grid category filters.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/pattern-directory#73]
We register a [`wporg-pattern-category`](https://github.com/WordPress/pattern-directory/blob/456b6a2bf0f03322fa1bfd74fcf4e310488306e8/public_html/wp-content/plugins/pattern-directory/includes/pattern-post-type.php#L57) which I assume will be assigned to block patterns and used as the sorting mechanism for the pattern grid menu here: #48.

Questions:
- Is that assumption correct? Will we be using those categories?
  - How will we manage localization? 
  - How can we control the order of how they appear?
- How will we manage the "context" messaging that appears when a user is looking at a specific category?
  - This PR just adds a temporary object (https://github.com/WordPress/pattern-directory/pull/65/files#diff-e8270c6022d0c897772f5a8dbb27343105f0f5f3d678fa1245176d6c6d17c936)
    - We'll want to make it more dynamic.

We could alternatively hardcode the items for now.

Related PR: #72

**Comment by ryelle** [comment]
> Is that assumption correct? Will we be using those categories? 

That is correct, those filters correspond to the categories. We'll launch with a set of categories, and users won't be able create new ones, only tag their patterns with the existing ones. I think it's likely we'll want to add new categories as the site grows, so I don't want to rely on a manual mapping if possible otherwise we'll always need a dev to update things.

I suppose we could add a "simple" ui to the term screen to manage up to 3 related terms, though?

I think @iandunn has some ideas here (https://github.com/WordPress/pattern-directory/issues/48#issuecomment-810418852) for more dynamic relationships.

I'd _assume_ that any related categories would come in as part of the term API response (for example, a field added by `register_rest_field` that lists an array of related term IDs or something).

> How will we manage localization?

Good question - maybe something like the Learn work that was just done? The logged out "create" page will also need handling for i18n, since it will be written in the editor too. I think our initial launch will just be in English, though.

> How will we manage the "context" messaging that appears when a user is looking at a specific category? 

The `45 <b>Header</b> patterns`? We should be able to build that dynamically with each page, using the total found posts + current filter name. We might need to tweak the data store to save the found posts total with the query results, though.

**Comment by StevenDufresne** [comment]
Some of these suggestions have been added to #76 and #78. We can move these conversations to the open PRs and future ones. Closing for now.
