### ISSUE TITLE
Theme: Block Preview card "copy" button should copy the block pattern.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/pattern-directory#88]
It should leverage code on the single pattern view page introduced in #74.

**Code Reference:**
https://github.com/WordPress/pattern-directory/blob/1c878592553a9dcc8f4f2c8cde05952436fe3f46/public_html/wp-content/themes/pattern-directory/src/components/copy-pattern-button/index.js#L13

**Thoughts**
We don't have designs for the "copy" action confirmation but maybe we could just update the button with a checkmark or copy? Maybe a toast?

Related to: #87

**Comment by ryelle** [comment]
Bringing over the conversation to this issue instead of [on the PR](https://github.com/WordPress/pattern-directory/pull/89), and will cc @shaunandrews

> Since there is very little space to confirm to the user that the action has succeeded, I decided to update the copy button on success from copy to copied and set a timeout to return to the original text after 3 seconds.

I found this mockup in the figma file, with a notice overlaid on the pattern preview — IMO this is a good solution to the issue (but it needs a closing X for accessibility (or [to display for 20+ hours](https://www.w3.org/WAI/WCAG21/Understanding/timing-adjustable.html), which seems a bit much 😁 ))

![Pattern Hover](https://user-images.githubusercontent.com/541093/116276015-1a941000-a752-11eb-8c84-fa85e13541af.png)

> It isn't clear to me what to do when copies fail. I've done some research and the command is fairly reliable.
> It can fail if the copied string is too long but it shouldn't really be triggered by patterns. Additionally, should the copy fail, the lack of response may be enough of a cue? We could turn the button red and the copy to 'Copy failed', maybe.

Hm, if copy fails, they have no way of using the patterns. I agree that this seems pretty reliable from my quick research, so I don't think it's something we need to work around for the initial launch, but let's pay attention to feedback and see if people are having copy troubles.

**Comment by shaunandrews** [comment]
> We don't have designs for the "copy" action confirmation but maybe we could just update the button with a checkmark or copy? 

Funny enough, that's actually what I had designed and implemented in the codepen (https://codepen.io/shaunandrews/pen/yLVjaWa?editors=1100).

![Inline Copy Button](https://user-images.githubusercontent.com/191598/116316223-9bb5cc00-a77f-11eb-8251-bd8cc1450d94.gif)

I wouldn't be opposed to also including a notice overlaid on the pattern, but I initially avoided it because I felt it obscured the pattern too much — and becomes problematic with shorter patterns and multiple interactive elements (like an "x" button) nested within each other.

Some sort of "snackbar" or "toast" (or whatever you call these things today) could be a good alternative but introduces issues with proximity to the action.

--

Do we think that updating the label on the button (from "Copy" to "Copied") is problematic on it's own? Do we _need_ any more messaging around this action in this context?

**Comment by ryelle** [comment]
> Do we think that updating the label on the button (from "Copy" to "Copied") is problematic on it's own?

If it's on a timeout like in your codepen, we still have the same a11y issue about timings, technically… but I think maybe a 20 second timeout might be enough. it's only one word to read, and if we leave it as "Copied" indefinitely, the user might have copied something else in that time. We'll also want to announce with `wp.a11y.speak` that the pattern was copied to the clipboard (this should happen on the details Copy button too).

**Comment by shaunandrews** [comment]
> we still have the same a11y issue about timings

Maybe. My reading of the linked W3 doc seems to be more about timed events that prevent you from continuing or otherwise interrupt a process.

In many ways, we're co-opting the button label to serve as a notice. I think ensuring that we announce the message (something like `aria-live` or similar) and have a sensible delay (20-30s seems like a good start) it will work well.

**Comment by StevenDufresne** [comment]
I've updated #89 to have a longer timeout and speak the action so we can see it. 

I'll defer to your a11y expertise, but from a non-a11y standpoint, I think it does a good enough job indicating that the pattern has been copied. We're also making the assumption that a user will want to copy a pattern via the preview, I'm not certain that will be where most patterns are copied. Part of me thinks the preview only needs the favorite action.... an assumption that maybe should be validated.

**Comment by ryelle** [comment]
> My reading of the linked W3 doc seems to be more about timed events that prevent you from continuing or otherwise interrupt a process.

It's about any timed content -- the user needs to be able to read and understand the content before it goes away. That particular page is examples, the text of the requirement is much more concise: ["Provide users enough time to read and use content."](https://www.w3.org/TR/WCAG21/#enough-time)
