### ISSUE TITLE
Pattern flags: Restrict the length of the Details string?

### ISSUE THREAD

**Issue by coreymckrill** [WordPress/pattern-directory#90]
When reporting a pattern (#83), a site visitor is asked to fill in a text area with details about why they are submitting a report/flag. Right now this field does not have character limit, other than that imposed by MYSQL. Since details are stored in `post_excerpt`, which is data type `text`, the character limit is [65,535](https://www.mysqltutorial.org/mysql-text/). This seems a bit excessive for our purposes.

We could add a sanitization callback while handling a flag submission that just automatically truncates the string down to a certain number of characters. Maybe 1000?

At the very least, we should probably truncate how much of the excerpt is rendered in the pattern flags list table.

**Comment by shaunandrews** [comment]
If we do restrict the length of the message we'll likely need to include some UI message when the length is reached — I wouldn't want to blindly truncate someones message without them knowing.

**Comment by ryelle** [comment]
I think this issue is solving for an issue we don't have yet, and so I keep punting it. I'm going to close it. Users can write an essay in the flag notes if they want, it shouldn't break anything. When whoever moderates reports sees that, either the user is using reporting in bad faith, or we need to add better instructions - but we won't know what that would look like until it's in use, and we can create new or reopen this issue then.
