### ISSUE TITLE
What happens if patterns use core blocks not present in Installed Gutenberg Version?

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/pattern-directory#91]
I feel like I saw a similar discussion somewhere but can't find it.

What happens in this scenario:

```
... pattern directory ships in Gutenberg X..
... current Gutenberg version Y
```

```
User A:
Creates 'CoolLayout' pattern using the core/SuperNewNetwork block that ships in Gutenberg Y.
```

```
User B:
Installs 'CoolLayout' pattern in Gutenberg X
```

I imagine the missing block view will be presented which typically offers the user the ability to install from the block directory, but since core block are not in the directory, the pattern won't work.

- Do we add metadata and filter these from the pattern search?
- Do we just improve Gutenberg messaging when a core block is missing?
- Do we also add core blocks to the pattern directory?

**Comment by ryelle** [comment]
Missing blocks in patterns uses the same error as when you disable a block plugin from existing content:

<img width="567" alt="screen-shot-2021-03-22-at-3 42 19-pm" src="https://user-images.githubusercontent.com/541093/116574915-2f041400-a8dc-11eb-9c62-6be5968fdcac.png">

If the block is in the pattern directory, it will let you opt to install it. If not, it'll just show the "convert or remove" text.

If User B is searching for patterns in their (outdated) WordPress site, the live preview will also be 'broken' — so they probably won't try to insert that block.

<img width="343" alt="Screen Shot 2021-04-29 at 12 19 04 PM" src="https://user-images.githubusercontent.com/541093/116584181-18ae8600-a8e5-11eb-898f-33448d0bd233.png">

IMO, I don't think new core blocks should go into the block directory, since the aim is that people should update to the latest versions. And would mean double the maintenance to keep those extra blocks updated.

**Comment by StevenDufresne** [comment]
> IMO, I don't think new core blocks should go into the block directory, since the aim is that people should update to the latest versions. And would mean double the maintenance to keep those extra blocks updated.

Yep, that's a good point.

> If User B is searching for patterns in their (outdated) WordPress site, the live preview will also be 'broken' — so they probably won't try to insert that block.

Assuming the "live preview" is the _error_ box the example, should we make it easier to remove broken blocks? I personally don't understand why I would "Keep as HTML" which seems to be my only obvious exit strategy. This also may be a better conversation to have in Gutenberg.

**Comment by ryelle** [comment]
> I personally don't understand why I would "Keep as HTML" which seems to be my only obvious exit strategy.

This makes more sense for the original use-case of this error: you wrote some posts, then removed a block plugin, but want to keep your existing content. Converting to HTML preserves the content (usually). I think it still makes _some_ sense in patterns - you want to preserve the pattern structure, but it's worth some discussion.

> This also may be a better conversation to have in Gutenberg.

Yeah, I think so - I did a quick search for existing issues and didn't see one, but I'm sure this has come up before.

**Comment by StevenDufresne** [comment]
Thanks for the information! I'll close this and reopen it in the Gutenberg project if necessary.

**Comment by StevenDufresne** [comment]
A similar issue was opened in Gutenberg: https://github.com/WordPress/gutenberg/issues/31706 and it references the pattern directory.
